
  const i18Obj = {
    'en': {
      'skills': 'Skills',
      'portfolio': 'Portfolio',
      'video': 'Video',
      'price': 'Price',
      'contacts': 'Contacts',
      'hero-title': 'Alexa Rise',
      'hero-text': 'Save sincere emotions, romantic feelings and happy moments of life together with professional photographer Alexa Rise',
      'hire': 'Hire me',
      'hire-span-1': 'H',
      'hire-span-2': 'i',
      'hire-span-3': 'r',
      'hire-span-4': 'e',
      'hire-span-5': ' ',
      'hire-span-6': 'm',
      'hire-span-7': 'e',
      'skill-title-1': 'Digital photography',
      'skill-text-1': 'High-quality photos in the studio and on the nature',
      'skill-title-2': 'Video shooting',
      'skill-text-2': 'Capture your moments so that they always stay with you',
      'skill-title-3': 'Rotouch',
      'skill-text-3': 'I strive to make photography surpass reality',
      'skill-title-4': 'Audio',
      'skill-text-4': 'Professional sounds recording for video, advertising, portfolio',
      'winter': 'Winter',
      'winter-span-1': 'W',
      'winter-span-2': 'i',
      'winter-span-3': 'n',
      'winter-span-4': 't',
      'winter-span-5': 'e',
      'winter-span-6': 'r',
      'spring': 'Spring',
      'spring-span-1': 'S',
      'spring-span-2': 'p',
      'spring-span-3': 'r',
      'spring-span-4': 'i',
      'spring-span-5': 'n',
      'spring-span-6': 'g',
      'summer': 'Summer',
      'summer-span-1': 'S',
      'summer-span-2': 'u',
      'summer-span-3': 'm',
      'summer-span-4': 'm',
      'summer-span-5': 'e',
      'summer-span-6': 'r',
      'autumn': 'Autumn',
      'autumn-span-1': 'A',
      'autumn-span-2': 'u',
      'autumn-span-3': 't',
      'autumn-span-4': 'u',
      'autumn-span-5': 'm',
      'autumn-span-6': 'n',
      'price-standart': 'Standard',
      'price-premium': 'Premium',
      'price-gold': 'Gold',
      'price-description-1-span-1': 'One location',
      'price-description-1-span-2': '120 photos in color',
      'price-description-1-span-3': '12 photos in retouch',
      'price-description-1-span-4': 'Readiness 2-3 weeks',
      'price-description-1-span-5': 'Make up, visage',
      'price-description-2-span-1': 'One or two locations',
      'price-description-2-span-2': '200 photos in color',
      'price-description-2-span-3': '20 photos in retouch',
      'price-description-2-span-4': 'Readiness 1-2 weeks',
      'price-description-2-span-5': 'Make up, visage',
      'price-description-3-span-1': 'Three locations or more',
      'price-description-3-span-2': '300 photos in color',
      'price-description-3-span-3': '50 photos in retouch',
      'price-description-3-span-4': 'Readiness 1 week',
      'price-description-3-span-5': 'Make up, visage, hairstyle',
      'phone': 'Phone',
      'message': 'Message',
      'order': 'Order shooting',
      'order-span-1': 'Or',
      'order-span-2': 'der',
      'order-span-3': ' ',
      'order-span-4': 'sh',
      'order-span-5': 'oo',
      'order-span-6': 'ti',
      'order-span-7': 'ng',
      'contact-me': 'Contact me',
      'send-message': 'Send message',
      'send-span-1': 'Se',
      'send-span-2': 'nd',
      'send-span-3': ' ',
      'send-span-4': 'me',
      'send-span-5': 'ss',
      'send-span-6': 'ag',
      'send-span-7': 'e',
      'control-desription': 'Please control the video playback using keyboard: Spacebar, Right Arrow and Left Arrow'
    },
    'ru': {
      'skills': 'Навыки',
      'portfolio': 'Портфолио',
      'video': 'Видео',
      'price': 'Цены',
      'contacts': 'Контакты',
      'hero-title': 'Алекса Райс',
      'hero-text': 'Сохраните искренние эмоции, романтические переживания и счастливые моменты жизни вместе с профессиональным фотографом',
      'hire': 'Пригласить',
      'hire-span-1': 'П',
      'hire-span-2': 'р',
      'hire-span-3': 'и',
      'hire-span-4': 'гл',
      'hire-span-5': 'а',
      'hire-span-6': 'си',
      'hire-span-7': 'ть',
      'skill-title-1': 'Фотография',
      'skill-text-1': 'Высококачественные фото в студии и на природе',
      'skill-title-2': 'Видеосъемка',
      'skill-text-2': 'Запечатлите лучшие моменты, чтобы они всегда оставались с вами',
      'skill-title-3': 'Ретушь',
      'skill-text-3': 'Я стремлюсь к тому, чтобы фотография превосходила реальность',
      'skill-title-4': 'Звук',
      'skill-text-4': 'Профессиональная запись звука для видео, рекламы, портфолио',
      'winter': 'Зима',
      'winter-span-1': '',
      'winter-span-2': 'З',
      'winter-span-3': 'и',
      'winter-span-4': 'м',
      'winter-span-5': 'а',
      'winter-span-6': '',
      'spring': 'Весна',
      'spring-span-1': 'В',
      'spring-span-2': 'е',
      'spring-span-3': 'с',
      'spring-span-4': 'н',
      'spring-span-5': 'а',
      'spring-span-6': '',
      'summer': 'Лето',
      'summer-span-1': '',
      'summer-span-2': 'Л',
      'summer-span-3': 'е',
      'summer-span-4': 'т',
      'summer-span-5': 'о',
      'summer-span-6': '',
      'autumn': 'Осень',
      'autumn-span-1': 'О',
      'autumn-span-2': 'с',
      'autumn-span-3': 'е',
      'autumn-span-4': 'н',
      'autumn-span-5': 'ь',
      'autumn-span-6': '',
      'price-standart': 'Стандартный',
      'price-premium': 'Премиум',
      'price-gold': 'Голд',
      'price-description-1-span-1': 'Одна локация',
      'price-description-1-span-2': '120 цветных фото',
      'price-description-1-span-3': '12 отретушированных фото',
      'price-description-1-span-4': 'Готовность через 2-3 недели',
      'price-description-1-span-5': 'Макияж, визаж',
      'price-description-2-span-1': 'Одна-две локации',
      'price-description-2-span-2': '200 цветных фото',
      'price-description-2-span-3': '20 отретушированных фото',
      'price-description-2-span-4': 'Готовность через 1-2 недели',
      'price-description-2-span-5': 'Макияж, визаж',
      'price-description-3-span-1': 'Три локации и больше',
      'price-description-3-span-2': '300 цветных фото',
      'price-description-3-span-3': '50 отретушированных фото',
      'price-description-3-span-4': 'Готовность через 1 неделю',
      'price-description-3-span-5': 'Макияж, визаж, прическа',
      'phone': 'Телефон',
      'message': '   Ваше сообщение',
      'order': 'Заказать съемку',
      'order-span-1': 'За',
      'order-span-2': 'ка',
      'order-span-3': 'за',
      'order-span-4': 'ть',
      'order-span-5': ' ',
      'order-span-6': 'съем',
      'order-span-7': 'ку',
      'contact-me': 'Свяжитесь со мной',
      'send-message': 'Отправить',
      'send-span-1': 'О',
      'send-span-2': 'т',
      'send-span-3': 'п',
      'send-span-4': 'р',
      'send-span-5': 'а',
      'send-span-6': 'ви',
      'send-span-7': 'ть',
      'control-desription': 'Пожалуйста, управляйте просмотром видео с помощью клавиш "Пробел", "Стрелка вправо" и "Стрелка влево"'
    }
  };


export default i18Obj;
